name: Frontend CI Pipeline

on:
  pull_request:
    branches: [ main, staging, dev ]
  push:
    branches: [ main, staging, dev ]

jobs:
  security-governance:
    name: Run Central Security & Governance Gate
    uses: 7-3-N-3-7/api/.github/workflows/trufflehog-scan.yml@main

  build-and-lint:
    name: Run Standard Frontend CI
    uses: 7-3-N-3-7/api/.github/workflows/standard-frontend-ci.yml@main
    needs: security-governance
